version: '3.8'
services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bibandcinedb
    ports:
      - 3308:3306
    volumes:
      - /home/user/db:/var/lib/mysql
    networks:
      - cinenetwork
  app:
    image: 883630/bibandcineapi:latest
    depends_on:
      - mysqldb
    build: 
      context: ./
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    volumes:
        - .m2:/root/.m2
    networks:
      - cinenetwork

volumes:
  db:


networks: 
  cinenetwork: